import = ["~/.config/alacritty/themes/themes/gruvbox.yaml"]
live_config_reload = true

[font]
size = 17.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
# decorations = "buttonless"
# dynamic_padding = false
# opacity = 0.8

# [window.padding]
# x = 18
# y = 16
